all: pruebashm pishm sumashm

pruebashm: pruebaShM.cc Semaforo.cc
	g++ pruebaShM.cc Semaforo.cc -o pruebashm

pishm: PiPorSeries.c
	gcc PiPorSeries.c -o pishm

sumashm: sumaUno.cc Semaforo.cc
	g++ sumaUno.cc Semaforo.cc -o sumashm